import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/layouts/Sidebar";
import Header from "@/components/layouts/Header/Header";

const epilogue = Epilogue({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <main>
          <div className="flex">
            <div className="hidden lg:block w-[18%] border-r-2">
              <Sidebar />
            </div>
            <div className="col-span-3 overflow-auto lg:col-span-5 lg:border-1 w-[82%]">
              <div className="px-5 py-6 lg:px-8">
                <Header />
                {children}
              </div>
            </div>
          </div>
        </main>
      </body>
    </html>
  );
}
